version: '3.5'
services:
  primecoind:
    build: .
    restart: always
    image: primecoind:next
    environment:
      - RPC_USER=primecoind
      - RPC_PASSWORD=primecoindrpc
    volumes:
      - type: bind
        source: /opt/primecoin/
        target: /data
    command:
      -txindex
      -rpcallowip=0/0.0.0.0
    ports:
      - '9911:9911'
      - '9912:9912'
      - '9913:9913'
      - '9914:9914'
