#variables are stored in .env file

version: "2"
services:
  localtestnet1:
    image: "${IMAGE}:${TAG}"
    expose:
      - 9903
      - 9904
    ports:
      - "19902:9904"
    #externalip is set in entrypoint-tor.sh
    entrypoint: /entrypoint-tor.sh
    command: -debug -rpcallowip=* -rpcpassword=bar -rpcuser=foo -testnet=1 -gen -bind=127.0.0.1 -proxy=127.0.0.1:9050 -listen -addnode=212.83.172.152:9903 -addnode=104.236.196.27:9903 -addnode=138.68.10.240:9903 -addnode=217.170.90.9:9903 -addnode=128.199.40.99:9903 -addnode=137.74.40.81:9903
    networks:
      testnet:
        aliases:
          - "localtestnet1"
networks:
  testnet:
