#variables are stored in .env file

version: "2"
services:
  localtestnet1:
    image: "${IMAGE}:${TAG}"
    expose:
      - 9903
      - 9904
    ports:
      - "19902:9904"
    #externalip is set in entrypoint-tor.sh
    entrypoint: /entrypoint-tor.sh
    command: -debug -rpcallowip=* -rpcpassword=bar -rpcuser=foo -testnet=1 -gen -bind=127.0.0.1 -proxy=127.0.0.1:9050 -listen
    networks:
      testnet:
        aliases:
          - "localtestnet1"
networks:
  testnet:
